routes/web.php
<?php

use App\Http\Controllers\Admin\AdminControler;
use App\Http\Controllers\Admin\AdminDiskusiControler;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MateriController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\DiskusiController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\JawabanController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/', [HomeController::class, 'index']);

Route::group(['middleware' => 'auth'], function() {
    Route::get('/profile', [HomeController::class, 'profile']);
});

Route::resource('diskusi', DiskusiController::class, [
            'only' => [
                'create',
                'store'
            ]
        ])
        ->middleware(['auth']);
Route::get('comment/{diskusi_id}', [JawabanController::class, 'create'])->name('comment-create')->middleware(['auth']);
Route::post('comment/store', [JawabanController::class, 'store'])->name('comment-store')->middleware(['auth']);

Route::resource('diskusi', DiskusiController::class, [
                'only' => [
                    'index',
                    'show'
                ]
            ]);
Route::post('upload/image', [ImageController::class, 'image'])->middleware('auth')->name('upload-karya');
Route::get('/course', [CourseController::class, 'index'])->name('course');

Route::prefix('admin')->middleware('admin')->group(function(){
    Route::get('/', [DashboardController::class, 'index'])->name('index-dashboard');
    Route::resource('/materi', MateriController::class);
    Route::resource('diskusi-admin', AdminDiskusiControler::class);
    Route::resource('user-admin', AdminControler::class);
});

require __DIR__.'/auth.php';

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('pages.dashboard.index');
    }
}

resources/views/pages/dashboard/admin/edit.blade.php
@extends('pages.dashboard.master')

@section('title')
    Edit Admin
@endsection

@push('addStyle')
    <style>
        .form-control{
            margin-bottom: 12px;
        }
    </style>
@endpush

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Admin</h1>
            </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Edit
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <form action="{{ route('user-admin.update', $item->id) }}" method="post">
                            @csrf
                            @method("PUT")
                            <label for="">Nama</label>
                            <input required type="text" class="form-control" value="{{ $item->name }}" name="name">
                            <label for="">Email</label>
                            <input required type="email" class="form-control" name="email" value="{{ $item->email }}">
                            <label for="">No Tlp</label>
                            <input required type="number" class="form-control" value="{{ $item->phone }}" name="phone">
                            <label for="">Bio</label>
                            <input required type="text" class="form-control" name="bio" value="{{ $item->bio }}">
                            <label for="">Password baru</label>
                            <input type="password" class="form-control" name="password" style="margin-bottom: 0px;">
                            <div class="" style="margin-bottom: 12px;">
                                <small >*Kosongkan jika tidak ingin di ubah</small>
                            </div>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
    </div>
@endsection

resources/views/pages/dashboard/admin/index.blade.php
@extends('pages.dashboard.master')

@section('title')
    Admin
@endsection



@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Admin</h1>
            </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Data Member
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>User</th>
                                        <th>Email</th>
                                        <th>No tlp</th>
                                        <th>edit </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($items as $item)
                                        <tr>
                                            <td>{{ $item->name }}</td>
                                            <td>{{ $item->email }}</td>
                                            <td>{{ $item->phone }}</td>
                                            <td>
                                                <div class="d-flex" style="display: flex">
                                                    <a href="{{ route('user-admin.edit', $item->id) }}" class="text-danger btn btn-link">Edit </a>
                                                    <span>
                                                        <form action="{{ route('user-admin.destroy' ,$item->id) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            <button type="submit" onclick="return confirm('Are you sure?')" class="text-danger btn btn-link">Hapus </button>
                                                        </form>
                                                    </span>
                                                </div>
                                            </td>
                                        </tr>
                                    @empty

                                    @endforelse

                                </tbody>
                            </table>
                        </div>
                        <button type="button" class="btn btn-primary">Save</button>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
    </div>
@endsection