routes/web.php
<?php

use App\Http\Controllers\Admin\AdminControler;
use App\Http\Controllers\Admin\AdminDiskusiControler;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MateriController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\DiskusiController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\JawabanController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/', [HomeController::class, 'index']);

Route::group(['middleware' => 'auth'], function() {
    Route::get('/profile', [HomeController::class, 'profile']);
});

Route::resource('diskusi', DiskusiController::class, [
            'only' => [
                'create',
                'store'
            ]
        ])
        ->middleware(['auth']);
Route::get('comment/{diskusi_id}', [JawabanController::class, 'create'])->name('comment-create')->middleware(['auth']);
Route::post('comment/store', [JawabanController::class, 'store'])->name('comment-store')->middleware(['auth']);

Route::resource('diskusi', DiskusiController::class, [
                'only' => [
                    'index',
                    'show'
                ]
            ]);
Route::post('upload/image', [ImageController::class, 'image'])->middleware('auth')->name('upload-karya');
Route::get('/course', [CourseController::class, 'index'])->name('course');

Route::prefix('admin')->middleware('admin')->group(function(){
    Route::get('/', [DashboardController::class, 'index'])->name('index-dashboard');
    Route::resource('/materi', MateriController::class);
    Route::resource('diskusi-admin', AdminDiskusiControler::class);
    Route::resource('user-admin', AdminControler::class);
});

require __DIR__.'/auth.php';

app/Models/Diskusi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Diskusi extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $table = 'diskusi';

    public function user(){
        return $this->belongsTo('App\Models\User');
    }

    public function jawaban()
    {
        return $this->hasMany('App\Models\Jawaban');
    }
}

app/Http/Controllers/Admin/DashboardController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index(){
        return view('pages.dashboard.index');
    }
}

app/Http/Controllers/DiskusiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Diskusi;
use App\Models\Jawaban;
use Illuminate\Http\Request;

class DiskusiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Diskusi::with('user')->withCount('jawaban')->paginate(2);

        return view('pages.diskusi.index', [
            'items' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.diskusi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $data['user_id'] = auth()->user()->id;

        $insert = Diskusi::create($data);

        return redirect()->route('diskusi.index')->with('msgSuccess', 'Berhasil membuat diskusi baru');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $diskusi = Diskusi::find($id);
        $data = Jawaban::with('user')->orderBy('id', 'desc')->where('diskusi_id', $id)->get();

        return view('pages.diskusi.detail', [
            'items' => $data,
            'diskusi' => $diskusi
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/dashboard/diskusi/edit.blade.php
@extends('pages.dashboard.master')

@section('title')
    edit diskusi
@endsection

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card" style="margin-top: 50px">
                <div class="card-body">
                    <div class="row justify-content-center">
                        <div class="col-md-8">
                            <form action="{{ route('diskusi-admin.update', $item->id) }}" method="POST">
                                @csrf
                                @method("PUT")
                                <label for="">Judul</label>
                                <input type="text" class="form-control" name="judul" value="{{ $item->judul }}">

                                <div class="" style="margin-top: 10px; margin-bottom: 10px">
                                    <label for="">Deskripsi</label>
                                    <textarea name="deskripsi" id="" cols="10" rows="10" class="mt-5 form-control" >{{ $item->deskripsi }}</textarea>
                                </div>

                                <button type="submit" class="btn btn-primary">Save</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/pages/dashboard/diskusi/index.blade.php
@extends('pages.dashboard.master')

@section('title')
    Admin Diskusi
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Diskusi</h1>
            </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Data form diskusi
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Judul Diskusi</th>
                                        <th>edit </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($items as $item)
                                        <tr>
                                            <td>{{ $item->judul }}</td>
                                            <td >
                                                <div class="d-flex" style="display: flex">
                                                    <a href="{{ route('diskusi-admin.edit', $item->id) }}" class="text-danger btn btn-link">Edit </a>
                                                    <span>
                                                        <form action="{{ route('diskusi-admin.destroy' ,$item->id) }}" method="post">
                                                            @csrf
                                                            @method('delete')
                                                            <button type="submit" onclick="return confirm('Are you sure?')" class="text-danger btn btn-link">Hapus </button>
                                                        </form>
                                                    </span>
                                                </div>
                                            </td>
                                        </tr>
                                    @empty
                                        <tr>
                                            <td colspan="4">
                                                <h4 class="text-center">Tidak ada data</h4>
                                            </td>
                                        </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                        <button type="button" class="btn btn-primary">Save</button>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
@endsection