routes/web.php
<?php

use App\Http\Controllers\Admin\AdminControler;
use App\Http\Controllers\Admin\AdminDiskusiControler;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MateriController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\DiskusiController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ImageController;
use App\Http\Controllers\JawabanController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/', [HomeController::class, 'index']);

Route::group(['middleware' => 'auth'], function() {
    Route::get('/profile', [HomeController::class, 'profile']);
});

Route::resource('diskusi', DiskusiController::class, [
            'only' => [
                'create',
                'store'
            ]
        ])
        ->middleware(['auth']);
Route::get('comment/{diskusi_id}', [JawabanController::class, 'create'])->name('comment-create')->middleware(['auth']);
Route::post('comment/store', [JawabanController::class, 'store'])->name('comment-store')->middleware(['auth']);

Route::resource('diskusi', DiskusiController::class, [
                'only' => [
                    'index',
                    'show'
                ]
            ]);
Route::post('upload/image', [ImageController::class, 'image'])->middleware('auth')->name('upload-karya');
Route::get('/course', [CourseController::class, 'index'])->name('course');

Route::prefix('admin')->middleware('admin')->group(function(){
    Route::get('/', [DashboardController::class, 'index'])->name('index-dashboard');
    Route::resource('/materi', MateriController::class);
    Route::resource('diskusi-admin', AdminDiskusiControler::class);
    Route::resource('user-admin', AdminControler::class);
});

require __DIR__.'/auth.php';

app/Models/Diskusi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Diskusi extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $table = 'diskusi';

    public function user(){
        return $this->belongsTo('App\Models\User');
    }

    public function jawaban()
    {
        return $this->hasMany('App\Models\Jawaban');
    }
}

app/Http/Controllers/DiskusiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Diskusi;
use App\Models\Jawaban;
use Illuminate\Http\Request;

class DiskusiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Diskusi::with('user')->withCount('jawaban')->paginate(2);

        return view('pages.diskusi.index', [
            'items' => $data
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.diskusi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $data['user_id'] = auth()->user()->id;

        $insert = Diskusi::create($data);

        return redirect()->route('diskusi.index')->with('msgSuccess', 'Berhasil membuat diskusi baru');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $diskusi = Diskusi::find($id);
        $data = Jawaban::with('user')->orderBy('id', 'desc')->where('diskusi_id', $id)->get();

        return view('pages.diskusi.detail', [
            'items' => $data,
            'diskusi' => $diskusi
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/diskusi/create.blade.php
@extends('layouts.front')

@section('title')
Buat Diskusi Baru
@endsection

@section('content')
<section>
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <h2 class="font-weight-bold mt-4" style="color:#1566B1;">Membuat Diskusi</h2>
            </div>
        </div>
        <form method="POST" action="{{ route('diskusi.store') }}">
            @csrf
            <div class="form-row">
                <div class="col">
                    <div class="form-group"><label>Judul</label><input class="shadow-none form-control inputan-diskusi"
                            type="text" placeholder="Judul Materi" required name="judul"></div>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <div class="form-group"><label>Isi Diskusi</label><textarea
                            class="shadow-none form-control inputan-diskusi" rows="5" placeholder="Masukan diskusi anda"
                            required name="deskripsi"></textarea></div>
                </div>
            </div>
            <div class="form-row">
                <div class="col text-center"><button class="btn" type="submit"
                        style="width:150px;background-color:#1566B1;color:#fff !important; border-radius:30px;margin-top:30px;">Post</button>
                </div>
            </div>
        </form>
    </div>
</section>
@endsection


@push('addScript')
<script src="assets/js/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="assets/js/sidebar.js"></script>
@endpush

resources/views/pages/diskusi/create_coment.blade.php
@extends('layouts.front')

@section('title')
Buat Diskusi Baru
@endsection

@section('content')
<section>
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <h2 class="font-weight-bold mt-4" style="color:#1566B1;">Membuat Diskusi</h2>
            </div>
        </div>
        <form method="POST" action="{{ route('comment-store') }}">
            @csrf
            <div class="form-row">
                <div class="col">
                    <div class="form-group"><label>Judul</label><input class="shadow-none form-control inputan-diskusi"
                            type="text" placeholder="Judul Materi" required name="judul"></div>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <div class="form-group"><label>Isi Diskusi</label><textarea
                            class="shadow-none form-control inputan-diskusi" rows="5" placeholder="Masukan diskusi anda"
                            required name="deskripsi"></textarea></div>
                </div>

                <input type="text" required name="diskusi_id" value="{{ $diskusi_id }}" hidden>
            </div>
            <div class="form-row">
                <div class="col text-center"><button class="btn" type="submit"
                        style="width:150px;background-color:#1566B1;color:#fff !important; border-radius:30px;margin-top:30px;">Post</button>
                </div>
            </div>
        </form>
    </div>
</section>
@endsection


@push('addScript')
<script src="assets/js/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="assets/js/sidebar.js"></script>
@endpush

resources/views/pages/diskusi/detail.blade.php
@extends('layouts.front')

@section('title')
{{ $diskusi->judul }}
@endsection

@section('content')
<section>
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <h2 class="font-weight-bold mt-4" style="color:#1566B1;">Detail Diskusi</h2>
                <h2 class="font-weight-bold mt-1" style="color:#1566B1;">{{ $diskusi->judul }}</h2>
            </div>
        </div>
        <div class="bg-white border-white shadow pl-3 pt-3 pr-3"
            style="padding-bottom:60px; border-radius:20px;margin-bottom:30px;">
            @forelse ($items as $item)
            <div class="row">
                <div class="col mb-4">
                    <div class="d-flex float-left align-items-center"><img
                            class="rounded-circle flex-shrink-0 mr-3 fit-cover" width="30" height="30" src="{{ url("storage/".$item->user->image)}}">
                        <div>
                            <h5 class="font-weight-bold text-dark mb-0">{{ $item->user->name }}</h5>
                        </div>
                    </div>
                    <p class="text-muted float-right">{{ \Carbon\Carbon::parse($item->created_at)->format('d-m-y') }}
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <h5 class="font-weight-bold mb-2">{{ $item->judul }}</h5>
                    <p class="text-black-50 mb-0"><span style="color: rgb(0, 0, 0);">{{ $item->deskripsi }}</span><br>
                    </p>
                    <div class="border-divinder"></div>
                </div>
            </div>
            @empty
            <h4 class="text-center">Tidak ada data</h4>
            @endforelse

            <div class="row">
                <div class="col text-center"><a class="btn btn-light button-comment" role="button"
                        href="{{ route('comment-create', $diskusi->id) }}">Comment&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                        &nbsp;<i class="fa fa-plus"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection

@push('addScript')
<script src="assets/js/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="assets/js/sidebar.js"></script>
@endpush

resources/views/pages/diskusi/index.blade.php
@extends('layouts.front')

@section('title')
Diskusi
@endsection

@section('content')
<section>
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <h2 class="font-weight-bold mt-4" style="color:#1566B1;">Diskusi</h2>
            </div>
        </div>
        <div class="row">
            <div class="col text-left mb-4">
                <a href="{{ route('diskusi.create') }}" class="btn"
                    style="width:270px;background-color:#1566B1;color:#fff !important; border-radius:30px;">Buat
                    Diskusi&nbsp;</a>
            </div>
        </div>

        @forelse ($items as $item)
        <div class="bg-white border-white shadow pl-3 pt-3 pr-3"
            style="padding-bottom:60px; border-radius:20px;margin-bottom:30px;">
            <div class="row">
                <div class="col mb-4">
                    <div class="d-flex align-items-center"><img class="rounded-circle flex-shrink-0 mr-3 fit-cover"
                            width="30" height="30" src="{{ url("storage/".$item->user->image) }}">
                        <div>
                            <h5 class="font-weight-bold text-dark mb-0">{{ $item->user->name }}</h5>
                        </div>
                    </div>
                </div>
            </div>
            <h5 class="font-weight-bold mb-2">{{ $item->judul }}</h5>
            <hr>
            <p class="mb-0">{{ $item->deskripsi }}s<br></p>
            <p class="text-muted float-left mt-4"><strong>{{ $item->jawaban_count }} Diskusi</strong><br></p><a
                class="float-right mt-4" href="{{ route('diskusi.show', $item->id) }}"><strong>Baca Diskusi</strong></a>
        </div>
        @empty
        <h4 class="text-center">Tidak ada diskusi</h4>
        @endforelse

    </div>
</section>
@endsection

@push('addScript')
<script src="assets/js/jquery.min.js"></script>
<script src="assets/bootstrap/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="assets/js/sidebar.js"></script>
@endpush